apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-nuvy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-nuvy
    app.kubernetes.io/part-of: ci10t-777-0092-app
  name: devfile-sample-nuvy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-nuvy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-nuvy
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0092-tenant/ci10t-777-0092-app/devfile-sample-nuvy@sha256:98dc0738f23bd26d4f8af73196f19434a06712decb84c0e1f2373b44edef4b96
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
